### ISSUE TITLE
ability to view log file as a web page 

### ISSUE THREAD

**Issue by cloudedturtle** [CptSpaceToaster/yeti#3]
Would like the ability to view the log file as a web page. May require additional hooks to the Log file call for proper formatting, etc.

**Comment by CptSpaceToaster** [comment]
It might be worth putting off this functionality, and writing a "smaller" servlet that interfaces with the Initium chat server on a more basic level. The firefox+selenium requirement seems to be a bit much when overhead is concerned.

We could serve the log there.

**Comment by CptSpaceToaster** [comment]
Closing this issue, and reopening it in [slatium](https://github.com/CptSpaceToaster/slatium/issues/1)
